# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spannerdiff < Formula
  desc ""
  homepage ""
  version "0.7.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/morikuni/spannerdiff/releases/download/0.7.0/spannerdiff_0.7.0_darwin_amd64.tar.gz"
      sha256 "4c439e6886b050b258a9350c33b45e4e7a2a0cc6f5c99b8ef44cfb79e6cb9304"

      def install
        bin.install "spannerdiff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/morikuni/spannerdiff/releases/download/0.7.0/spannerdiff_0.7.0_darwin_arm64.tar.gz"
      sha256 "25e09e8391fe15fa988a8def8533881f7b5a9d72dbf946717b62f43a7fb2dd0f"

      def install
        bin.install "spannerdiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/morikuni/spannerdiff/releases/download/0.7.0/spannerdiff_0.7.0_linux_amd64.tar.gz"
        sha256 "8ba7d7b9247f48c5571be588a6b227f96fefbbed5087c878d742fd4d0916c62c"

        def install
          bin.install "spannerdiff"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/morikuni/spannerdiff/releases/download/0.7.0/spannerdiff_0.7.0_linux_arm64.tar.gz"
        sha256 "08321cf854bdbe1f4043b43cc09c62afbc3267863d74708d32222755636f3eb9"

        def install
          bin.install "spannerdiff"
        end
      end
    end
  end
end
