# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spannerdiff < Formula
  desc ""
  homepage ""
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/morikuni/spannerdiff/releases/download/0.4.0/spannerdiff_0.4.0_darwin_amd64.tar.gz"
      sha256 "a3a2e7f46a479cd48e0974c1432d266afb72c7ba053792da78e6e9ea0cd589fa"

      def install
        bin.install "spannerdiff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/morikuni/spannerdiff/releases/download/0.4.0/spannerdiff_0.4.0_darwin_arm64.tar.gz"
      sha256 "ae6928649cfedbb633e60505019c0223d0384a04efeaa38cd8f7de70e1ca51be"

      def install
        bin.install "spannerdiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/morikuni/spannerdiff/releases/download/0.4.0/spannerdiff_0.4.0_linux_amd64.tar.gz"
        sha256 "aaab9a786ffef85b9a3bede16c40f078d154467b61010cff244c3bb15fa3878f"

        def install
          bin.install "spannerdiff"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/morikuni/spannerdiff/releases/download/0.4.0/spannerdiff_0.4.0_linux_arm64.tar.gz"
        sha256 "26e715500dbc84a5cc32ec07ec75bf48b8c03798ab10bff86c363f021b18db05"

        def install
          bin.install "spannerdiff"
        end
      end
    end
  end
end
